# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go api tests

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
          image: mysql:8
          env:
              MYSQL_DATABASE: mysqldb
              MYSQL_USER: root.
              MYSQL_PASSWORD: bankapi18
              MYSQL_ROOT_PASSWORD: bankapi18
          ports:
              - 5432:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Clone repository into runner    
      uses: actions/checkout@v3
    
    - name: Install Golang-migrate
      run:  | 
           curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
           sudo mv migrate /usr/bin/
           which migrate

    - name: Migrations
      run:  cd ./db && make migrateup

    - name: Run tests
      run: cd ./db && make gotest
